// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth/next";
import 'svgmap/dist/svgMap.min.css';

// 1. Perbaiki path ke globals.css
import "@/styles/globals.css"; 

// 2. Hapus impor Header dan Footer
// import Header from "@/components/partials/Header";
// import Footer from "@/components/partials/Footer";

// 3. Impor Provider baru
import SessionProvider from "@/utils/SessionProvider";
import Providers from "@/Providers";
import SessionTimeoutWrapper from "@/components/SessionTimeoutWrapper";
import { ThemeProvider } from "@/providers/ThemeProvider"; // <-- Impor ThemeProvider

const inter = Inter({ subsets: ["latin"] });

// Saya gunakan metadata dari kode Anda
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    // 4. Hapus 'data-theme' dan tambahkan 'suppressHydrationWarning'
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* 5. Bungkus semua provider dengan ThemeProvider */}
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider session={session}>
            <SessionTimeoutWrapper />
            {/* <Header /> <-- 6. HAPUS Header dari sini */}
            <Providers>
              {children} 
            </Providers>
            {/* <Footer /> <-- 7. HAPUS Footer dari sini */}
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}